### ISSUE TITLE
requirements.txt problem

### ISSUE THREAD

**Issue by Heracrotix** [alpharaoh/AmongUsBot#5]
The cmd says "No such file or directory: 'requirements.txt'" whenever i try to do step 6.  I'm in the right file, and I unzipped it properly and what not. Any idea why this might be 
![Error](https://user-images.githubusercontent.com/46072242/93001448-00782b00-f4fd-11ea-86ba-9a94b755f8fd.PNG)
happening?

**Comment by CAP1Sup** [comment]
Open Powershell and navigate to the Among Us bot directory like you did before. If you run an “ls” command, does the requirements.txt show up?

**Comment by CAP1Sup** [comment]
Try downloading from the main code page instead of from releases
