### ISSUE TITLE
i redid the token two times..

### ISSUE THREAD

**Issue by shortguy123** [alpharaoh/AmongUsBot#7]
Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1124)')]

You have an invalid bot token in config.py

**Comment by denverquane** [comment]
Yeah that's a problem with the Discord Python library, not the bot token.

Fix is here: https://github.com/Rapptz/discord.py/issues/4159#issuecomment-640107584

**Comment by shortguy123** [comment]
thanks it works now
